version: "3.8"

services:
  postgres:
      image: postgres:15
      environment:
        POSTGRES_USER: demo
        POSTGRES_PASSWORD: demo
        POSTGRES_DB: secretmanager
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - default
  openbao:
    image: quay.io/openbao/openbao:2.1.0
    container_name: openbao
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./config:/openbao/config
      - ./data:/openbao/file
      - ./logs:/openbao/logs
    environment:
      - OPENBAO_MODE=dev
      - BAO_LOCAL_CONFIG={
        "listener":[{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}],
        "storage":{"file":{"path":"/openbao/file"}}
        }
      - BAO_TOKEN_FILE=/openbao/file/.bao_token
    command: server
    restart: unless-stopped
    networks:
        - default
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgres://demo:demo@postgres:5432/secretmanager
      - OPENBAO_URL=http://openbao:8200
      - BAO_TOKEN_FILE=/openbao/file/.bao_token
    depends_on:
      - postgres
      - openbao
    volumes:
      - ./data:/openbao/file
    ports:
      - "5000:5000"
    networks:
        - default

  volumes:
    pgdata:
