services:
  postgres:
      image: postgres:15
      environment:
        POSTGRES_USER: demo
        POSTGRES_PASSWORD: demo
        POSTGRES_DB: secretmanager
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - default
  openbao:
    image: quay.io/openbao/openbao:2.1.0
    container_name: openbao
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./openbao/data:/openbao/file
      - ./openbao/logs:/openbao/logs
    environment:
      - BAO_API_ADDR=http://openbao:8200
      - BAO_LOCAL_CONFIG={"listener":[{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}],"storage":{"file":{"path":"/openbao/file"}}}
    command: server
    restart: unless-stopped
    networks:
        - default
  openbao-init:
    build:
      context: ./openbao
      dockerfile: Dockerfile.init
    container_name: openbao-init
    depends_on:
      - openbao
    volumes:
      - ./openbao/data:/openbao/file
      - ./openbao/logs:/openbao/logs
    entrypoint: ["/openbao/init_openbao.sh"]
    restart: "no"
    environment:
      - OPENBAO_URL=http://openbao:8200
      - BAO_FILE=/openbao/file/.bao_token
    networks:
      - default
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgres://demo:demo@postgres:5432/secretmanager
      - OPENBAO_URL=http://openbao:8200
      - BAO_TOKEN_FILE=/openbao/file/.bao_token
    volumes:
      - ./openbao/data:/openbao/file
    ports:
      - "5000:5000"
    networks:
      - default
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
