services:
  openbao:
    image: quay.io/openbao/openbao:2.1.0
    container_name: openbao-dev
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"
      - "8201:8201"
    volumes:
      - ./config:/openbao/config
      - ./data:/openbao/file
      - ./logs:/openbao/logs
    environment:
      - BAO_LOCAL_CONFIG={"listener":[{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}],"storage":{"file":{"path":"/openbao/file"}}}
      - BAO_TOKEN_FILE=/openbao/file/.bao_token
    command: "server -dev -dev-root-token-id=root"
    restart: unless-stopped
    networks:
        - openbao-net
networks:
  openbao-net:

volumes:
  data:
  logs:
