services:
  postgres:
      image: postgres:15
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - default
  openbao:
    image: quay.io/openbao/openbao:2.1.0
    container_name: openbao
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./openbao/data:/openbao/file
      - ./openbao/logs:/openbao/logs
      - ./openbao/policies:/openbao/policies
    environment:
      - BAO_API_ADDR=${OPENBAO_URL}
      - BAO_LOCAL_CONFIG={"listener":[{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}],"storage":{"file":{"path":"/openbao/file"}}}
    command: server
    restart: unless-stopped
    networks:
        - default
  openbao-init:
    build:
      context: ./openbao
      dockerfile: Dockerfile.init
    container_name: openbao-init
    depends_on:
      - openbao
    user: "0:0"
    volumes:
      - ./openbao/data:/openbao/file
      - ./openbao/logs:/openbao/logs
      - ./openbao/policies:/openbao/policies
    entrypoint: ["/openbao/init_openbao.sh"]
    restart: "no"
    environment:
      - OPENBAO_URL=${OPENBAO_URL}
      - BAO_TOKEN_FILE=${BAO_TOKEN_FILE}
    networks:
      - default
  core_service:
    command: >
      bash -c "python3 manage.py migrate && python manage.py setup_test_data && python3 manage.py runserver 0.0.0.0:5000"
    build: ./backend/core
    container_name: core_service
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - OPENBAO_URL=${OPENBAO_URL}
      - BAO_TOKEN_FILE=${BAO_TOKEN_FILE}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PORT=5000
    volumes:
      - ./openbao/data:/openbao/file
    ports:
      - "5000:5000"
    depends_on:
      - openbao
      - openbao-init
      - postgres
    networks:
      - default
  notify_service:
    command: >
      bash -c "python3 run.py"
    build: ./backend/notify_service
    container_name: notify_service
    depends_on:
      - core_service
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    networks:
      - default
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - default
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

volumes:
  pgdata:

networks:
  default:
