FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

RUN mkdir /app/log/
RUN echo "" > /app/log/secret_manager.log
COPY . /app

CMD ["python3", "run.py"]
